(function($R)
{
    $R.lang['nl'] = {
        "format": "Opmaak",
        "image": "Afbeelding",
        "file": "Bestand",
        "link": "Link",
        "bold": "Vet",
        "italic": "Cursief",
        "deleted": "Doorstreept",
        "underline": "Onderstreept",
        "superscript": "Superscript",
        "subscript": "Subscript",
        "bold-abbr": "B",
        "italic-abbr": "I",
        "deleted-abbr": "S",
        "underline-abbr": "U",
        "superscript-abbr": "Sup",
        "subscript-abbr": "Sub",
        "lists": "Lijsten",
        "link-insert": "Link invoegen",
        "link-edit": "Link Bewerken",
        "link-in-new-tab": "Open link in nieuw tabblad",
        "unlink": "Ontkoppelen",
        "cancel": "Annuleren",
        "close": "Afsluiten",
        "insert": "Invoegen",
        "save": "Opslaan",
        "delete": "Verwijder",
        "text": "Tekst",
        "edit": "Bewerken",
        "title": "Titel",
        "paragraph": "Normale tekst",
        "quote": "Citaat",
        "code": "Code",
        "heading1": "Koptekst 1",
        "heading2": "Koptekst 2",
        "heading3": "Koptekst 3",
        "heading4": "Koptekst 4",
        "heading5": "Koptekst 5",
        "heading6": "Koptekst 6",
        "filename": "Bestandsnaam",
        "optional": "Optioneel",
        "unorderedlist": "Ongeordende lijst",
        "orderedlist": "Geordende lijst",
        "outdent": "Uitspringen",
        "indent": "Inspringen",
        "horizontalrule": "Streep",
        "upload": "Upload",
        "upload-label": "Sleep bestanden naar dit vak of klik om bestanden toe te voegen",
        "upload-change-label": "Zet een nieuwe afbeelding neer om te wijzigen",
        "accessibility-help-label": "RTF editor",
        "caption": "Onderschrift",
        "bulletslist": "Lijst met opsommingstekens",
        "numberslist": "Genummerde lijst",
        "image-position": "Positie",
        "none": "Geen",
        "left": "Links",
        "right": "Rechts",
        "center": "Centreren",
        "undo": "Ongedaan maken",
        "redo": "Opnieuw"
    };
})(Redactor);